server:
  port: 8085
spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/crm_employee?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}